### PR TITLE
[test] add Kamelet errorHandler test

### PR DESCRIPTION
**Pull request by bouskaJ**

### CODE REVIEW

**Comment by heiko-braun** [comment]
Thanks @bouskaJ. Is this backported from upstream?

**Comment by bouskaJ** [comment]
It's part of https://issues.redhat.com/browse/FUSEQE-13590. The upstream PR was not yet merged because of https://github.com/apache/camel-k/issues/2525 (see https://github.com/apache/camel-k/pull/2522). As it's working on the PROD build and FUSEQE-13590 is set to `critical` + `camel-k-GA` I think we should merge it.

**Comment by squakez** [comment]
I am thinking if it makes sense to have it here before merging it upstream. If we keep both PRs we won't be in the position to keep repositories aligned as commits are diverging. I think in this case we can merge this but we need to close the [upstream PR](https://github.com/apache/camel-k/pull/2522) and cherry pick this commit into upstream once #2525 is fixed. Are we good with this approach?

**Review by squakez — APPROVED** [review]

**Comment by bouskaJ** [comment]
> I am thinking if it makes sense to have it here before merging it upstream. If we keep both PRs we won't be in the position to keep repositories aligned as commits are diverging. I think in this case we can merge this but we need to close the [upstream PR](https://github.com/apache/camel-k/pull/2522) and cherry pick this commit into upstream once [apache#2525](https://github.com/apache/camel-k/issues/2525) is fixed. Are we good with this approach?

I don't know the upstream-downstream sync process, so do whatever works for you.

**Comment by squakez** [comment]
@heiko-braun what do you suggest? do you think it's okey if we merge this and we eventually pick this commit into upstream once https://github.com/apache/camel-k/issues/2525 is fixed?

**Comment by bouskaJ** [comment]
@heiko-braun can we move it forward?

**Comment by squakez** [comment]
I've just fixed the `main` via https://github.com/apache/camel-k/pull/2564, we can merge it upstream and then cherry-pick the commit in order to have a cleaner process.

**Comment by squakez** [comment]
Closed in favour of #64

**Pull request closed without merging**
