### PR TITLE
CMLK-1872: Fix manifest generation: don't modify the labels of selector (2.2.x)

### PR DESCRIPTION
**Pull request by claudio4j**
CMLK-1872 Upgrade test olm_upgrade_test.go fails with no operators found in channel stable-v2 
https://issues.redhat.com/browse/CMLK-1872

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by squakez** [comment]
Wondering if it makes sense to have this upstream as well, wdyt?

**Comment by squakez** [comment]
Just checked https://gitlab.cee.redhat.com/fuse-camel-k/fuse-camel-k-image/-/merge_requests/1015 and I have the feeling this merge is causing this failure. I've tried to `make bundle` and it really fails with the following error:
```
FATA[0000] [error loading objs in directory: invalid bundle: contains multiple CSVs, no bundle csv found, unable to load bundle from directory bundle/manifests] 
make: *** [Makefile:574: bundle] Error 1
```
Please have a look and test the fix against the `make bundle` whenever it affects CRDs.

**Comment by claudio4j** [comment]
I will have a look, thanks.

**Comment by claudio4j** [comment]
> Wondering if it makes sense to have this upstream as well, wdyt?

The issue affects the OLM upgrade from 1.10 to 2.x since the `app: camel-k` label was added in 2.0 to all metadata and the selector `matchLabels` should be immutable to support a clean upgrade, but as camel-k is already in 2.3 development, I am unsure if this still makes sense for upstream.

**Comment by claudio4j** [comment]
Also, if we add this to 2.3 upstream, it would change again the matchLabels to remove the `app: camel-k` label, so an OLM upgrade from 2.2 to 2.3 will fail.

**Pull request merged**
