### PR TITLE
CMLK-1589 - mandatory openshift annotations for bundle operator metadata

### PR DESCRIPTION
**Pull request by gansheer**
**Release Note**
```release-note
CMLK-1589 - mandatory openshift annotations for bundle operator metadata
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by squakez — COMMENTED** [review]
In theory we are FIPS compliant no matter what's the runtime chosen by the user.

**Comment by claudio4j** [comment]
Are these annotations to go to a 2.2.x branch too ?

**Comment by gansheer** [comment]
> Are these annotations to go to a 2.2.x branch too ?

Yes, but with 2.x I am wondering if some of them should go upstream

**Review by claudio4j — APPROVED** [review]

**Comment by gansheer** [comment]
> In theory we are FIPS compliant no matter what's the runtime chosen by the user.

I can set it to `true` for now and we see how the CI pipeline react ? If it is not good we can rollback to `false` after.

**Comment by gansheer** [comment]
> I can set it to `true` for now and we see how the CI pipeline react ? If it is not good we can rollback to `false` after.

Done.

**Pull request merged**
