### PR TITLE
fix(cli): resource path with quotes and spaces

### PR DESCRIPTION
**Pull request by squakez**

### CODE REVIEW

**Comment by squakez** [comment]
@apupier, this one should fix the issue with `--resource` quotes and spaces. Mind having a look as soon as the new build is complete?

**Comment by apupier** [comment]
tried with a local build. Now I have this error:
`Error: stat "/home/apupier/ws/camelk-test/direct-endpoint-test.xml": no such file or directory`

**Comment by squakez** [comment]
It seems this is happening because the `"` characters are processed as part of the file. In the CLI the same behavior is replicated when we escape the `"`, ie `kamel run --resource \"resources-data.txt\" `. Basically we don't expect a double quote as part of the parameter. I am pretty sure the same would happen for any other parameter, ie the route source itself. Just to make sure, can you test a route with double quotes? ie the equivalent of `kamel run "/path to/resource-file-route.groovy"`

**Comment by apupier** [comment]
it is working when putting quotes around the java file:

```
(base) [apupier@localhost camel-k-productized]$ ./kamel run "/home/apupier/ws/camelk-test/DemoTest.java"
integration "demo-test" created
```

**Comment by apupier** [comment]
as discussed in private chat, this was not working with kamel 1.4.0 neither. (and good chance that it has never worked) so no regression detected based on the refactor.
Reported https://issues.redhat.com/browse/FUSETOOLS2-1172 to track the problem on VS Code Camel K side

**Pull request merged**
