### PR TITLE
Updates for metadata bundle generation

### PR DESCRIPTION
**Pull request by phantomjinx**

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]

**Review by squakez — CHANGES_REQUESTED** [review]
Thanks for committing the changes. However, this one will create divergences with the upstream and won't be available when we switch to following minor or major. In order to keep it in sync, we should handle any of these changes in the init/sync scripts in https://gitlab.cee.redhat.com/cpaas-products/camelk/-/tree/1.8.x/sync.

**Comment by phantomjinx** [comment]
> Thanks for committing the changes. However, this one will create divergences with the upstream and won't be available when we switch to following minor or major. In order to keep it in sync, we should handle any of these changes in the init/sync scripts in https://gitlab.cee.redhat.com/cpaas-products/camelk/-/tree/1.8.x/sync.

Am not sure how that process joins up with generating the bundle metadata.
The bundle generation works as follows:
* Checkout out this repository
* Execute `make clean bundle` which generates a `bundle` directory containing the metadata
* Checkout the metadata bundle repository
* Compare the `bundle` directory with the bundle repostory using a diff tool, eg. meld
* If the generation rules in the Makefile are out-of-date for some reason then make a commit to update the camel-k source repo
* If the bundle directory is out-of-date then make a commit to update the bundle repo

Both repositories are then brought in sync.

As far as downstream v upstream, there are certain changes, eg. to the base CSV, that should exist only downstream, eg. changing Apache -> Red Hat Integration. These need to exist in this repo prior to the release to allow the above bundle generation process.

**Review by phantomjinx — COMMENTED** [review]
Review of changes
* PROJECT - package name only applicable to downstream and should be committed
* Controller-gen version increment in CRDs - can go upstream
* kustomization.yaml / redhat-label-patch - only applicable to downstream
* References to image url only applicable to downstream
* CSV - description changes, skipRange, maintainer properties - only appliable to downstream
* CSV - all versions should say X.Y.Z as this is the base template
* CSV - minkubeversion should probably go upstream
* Makefile - improvements taken from 1.6 branch so some can go upstream if not there already.
* Makefile - IMAGE_NAME  / GIT_REMOTE / ADD_REDHAT_LABELS_PATCH -  downstream only
* Makefile - pre-bundle rule can go upstream
*

**Comment by squakez** [comment]
Any divergence within Camel K repository should go here: https://gitlab.cee.redhat.com/cpaas-products/camelk/-/blob/1.8.x/sync/camel-k-init.sh#L44

As you can see it's there where we're adding any customized Red Hat specification such as the bundle configuration changes. If there is any need to have the change in the upstream Makefile, then, it would be better to make the change upstream and later backport (manually or automatically if it is also backported to any of the `release-a.b.x` upstream branches).

**Comment by phantomjinx** [comment]
> Any divergence within Camel K repository should go here: https://gitlab.cee.redhat.com/cpaas-products/camelk/-/blob/1.8.x/sync/camel-k-init.sh#L44
> 
> As you can see it's there where we're adding any customized Red Hat specification such as the bundle configuration changes. If there is any need to have the change in the upstream Makefile, then, it would be better to make the change upstream and later backport (manually or automatically if it is also backported to any of the `release-a.b.x` upstream branches).

Alright. I'll see if I can split this PR into `camel-k-init.sh` and upstream.

**Comment by squakez** [comment]
Great, let me know if you need any help. Also, feel free to improve the script with any enhancement you feel is required. I am not a top level bash script developer, so, there is for sure room for improvement.

**Comment by phantomjinx** [comment]
Upstream PR submitted -> https://github.com/apache/camel-k/pull/3423

Downstream merge request submitted -> https://gitlab.cee.redhat.com/cpaas-products/camelk/-/merge_requests/20

**Pull request closed without merging**
