### PR TITLE
Adds post bundle generation script

### PR DESCRIPTION
**Pull request by phantomjinx**
* post_bundle_gen.sh
 * Appends extra RH labels to the generated bundle Dockerfile

* Makefile
 * Calls the post_bundle script at the end of the bundle generation process

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by phantomjinx** [comment]
@squakez 
Does this need to go back on `release-1.8` as well?

**Comment by squakez** [comment]
`release-1.9.x` is something experimental, we need this for `release-1.8.x` only. I wonder if we should instead having this upstream, and let the sync take care of it. Does it make sense for the community?

**Comment by phantomjinx** [comment]
> `release-1.9.x` is something experimental, we need this for `release-1.8.x` only. I wonder if we should instead having this upstream, and let the sync take care of it. Does it make sense for the community?

That's the difficulty. These labels really are for RH use only. They've just not been required upstream in any context, going back to Syndesis.

I'll do a separate PR for 1.8.

**Comment by phantomjinx** [comment]
I'll leave it to you whether you want this on 1.9. If not, close as your discretion.

**Comment by squakez** [comment]
Thanks @phantomjinx, then we need to only fix downstream in `release-1.8.x`.

**Pull request closed without merging**
